# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/AoC_2022',
                'doc_host': 'https://ctwardy.github.io',
                'git_url': 'https://github.com/ctwardy/AoC_2022',
                'lib_path': 'AoC_2022'},
  'syms': {'AoC_2022.core': {'AoC_2022.core.foo': ('core.html#foo', 'AoC_2022/core.py')}}}
