# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/day6.ipynb.

# %% auto 0
__all__ = ['get_pos_firstn_uniq']

# %% ../nbs/day6.ipynb 9
#| code-fold: true
def get_pos_firstn_uniq(s: str,   # The string with the packet or message
                        n: int=4  # How many chars make up the packet or message
                       ) -> int:  # Index of char after the first n uniq chars
    """Find the first n unique chars in the string. Return index of next char."""
    for i in range(len(s) - n):
        _ = s[i:i+n]
        if len(set(_)) == n:
            return  i+n
